name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pest:
    name: PEST - PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4, 8.3, 8.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run PEST (with coverage)
        run: composer test:coverage
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run PHPStan
        run: composer phpstan -- --error-format=github
  pint:
    name: Pint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **.php
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run Pint
        run: composer pint -- ${{ steps.changed-files.outputs.all_changed_files }} --test -v
